/**
 * Curated sample places for the hackathon demo.
 * Names are illustrative; `perk` marks where a partner discount/coupon would appear once real
 * local businesses are onboarded. Reservation links go to a Naver search for the place.
 */
export interface PlaceSeed {
  id: string;
  name: string;
  category: "음식점" | "카페" | "술집" | "보드게임카페" | "방탈출" | "기타";
  region: string;
  address: string;
  capacityMax: number;
  priceLevel: 1 | 2 | 3;
  rating: number;
  tags: string[];
  perk: string | null;
  /** Opening hour (0-24) and closing hour (may exceed 24 for after-midnight). */
  openFrom: number;
  openTo: number;
}

type Row = [
  name: string,
  category: PlaceSeed["category"],
  capacityMax: number,
  priceLevel: 1 | 2 | 3,
  rating: number,
  tags: string[],
  perk: string | null,
  openFrom: number,
  openTo: number,
];

const REGION_DATA: Record<string, { area: string; rows: Row[] }> = {
  성수: {
    area: "서울 성동구 성수동",
    rows: [
      [
        "성수 온기 다이닝",
        "음식점",
        8,
        2,
        4.4,
        ["룸", "파스타", "분위기"],
        "미팅 참가자 사이드 메뉴 1개 무료",
        11,
        22,
      ],
      [
        "연무장 로스터리",
        "카페",
        10,
        1,
        4.3,
        ["넓은 좌석", "디저트", "사진"],
        null,
        9,
        22,
      ],
      [
        "성수 하이볼 클럽",
        "술집",
        10,
        2,
        4.2,
        ["하이볼", "단체석", "음악"],
        "첫 잔 10% 할인",
        17,
        26,
      ],
      [
        "보드 앤 라떼 성수",
        "보드게임카페",
        8,
        1,
        4.5,
        ["보드게임", "아이스브레이킹"],
        "2시간 이용 1시간 무료 연장",
        12,
        24,
      ],
      [
        "성수 미스터리 룸",
        "방탈출",
        6,
        2,
        4.6,
        ["협동", "추리"],
        "4인 이상 5% 할인",
        10,
        23,
      ],
    ],
  },
  건대: {
    area: "서울 광진구 화양동",
    rows: [
      [
        "건대 화로 한상",
        "음식점",
        12,
        2,
        4.1,
        ["고기", "단체", "가성비"],
        null,
        11,
        24,
      ],
      [
        "커먼 그라운드 카페",
        "카페",
        12,
        1,
        4.0,
        ["넓은 좌석", "콘센트"],
        null,
        8,
        23,
      ],
      [
        "건대 포차 골목집",
        "술집",
        14,
        1,
        4.2,
        ["단체석", "안주", "가성비"],
        "안주 1종 서비스",
        16,
        27,
      ],
      [
        "플레이 보드 건대",
        "보드게임카페",
        10,
        1,
        4.4,
        ["보드게임", "게임 설명"],
        null,
        11,
        24,
      ],
      [
        "건대 스퀘어 볼링",
        "기타",
        12,
        1,
        4.1,
        ["볼링", "활동"],
        "2게임 이용 시 음료 제공",
        11,
        25,
      ],
    ],
  },
  강남: {
    area: "서울 강남구 역삼동",
    rows: [
      [
        "강남 라운지 비스트로",
        "음식점",
        8,
        3,
        4.5,
        ["룸", "코스", "기념일"],
        null,
        11,
        23,
      ],
      [
        "역삼 브루잉 스튜디오",
        "카페",
        8,
        2,
        4.3,
        ["조용한", "브런치"],
        null,
        8,
        22,
      ],
      [
        "강남 와인 앤 바이트",
        "술집",
        8,
        3,
        4.4,
        ["와인", "분위기", "룸"],
        "와인 병당 5천원 할인",
        18,
        26,
      ],
      [
        "테이블 플레이 강남",
        "보드게임카페",
        8,
        2,
        4.3,
        ["보드게임", "룸"],
        null,
        12,
        24,
      ],
      [
        "강남 이스케이프 랩",
        "방탈출",
        6,
        2,
        4.7,
        ["추리", "인기"],
        "미팅 참가자 전용 시간대 예약",
        10,
        24,
      ],
    ],
  },
  홍대: {
    area: "서울 마포구 서교동",
    rows: [
      [
        "홍대 골목 식당",
        "음식점",
        10,
        2,
        4.2,
        ["분위기", "단체", "이색"],
        null,
        11,
        23,
      ],
      [
        "연남 감성 카페",
        "카페",
        8,
        1,
        4.4,
        ["사진", "디저트", "포토존"],
        "디저트 세트 10% 할인",
        10,
        23,
      ],
      [
        "홍대 라이브 펍",
        "술집",
        16,
        2,
        4.3,
        ["라이브 음악", "단체석"],
        null,
        17,
        27,
      ],
      [
        "홍대 보드게임 아지트",
        "보드게임카페",
        12,
        1,
        4.6,
        ["보드게임", "대규모"],
        "3시간 이상 이용 시 음료 1잔",
        12,
        25,
      ],
      [
        "홍대 노래 스튜디오",
        "기타",
        8,
        1,
        4.0,
        ["노래방", "단체"],
        null,
        12,
        27,
      ],
    ],
  },
  신촌: {
    area: "서울 서대문구 창천동",
    rows: [
      [
        "신촌 돈가스 하우스",
        "음식점",
        10,
        1,
        4.1,
        ["가성비", "든든한"],
        "음료 무료 리필",
        11,
        22,
      ],
      [
        "신촌 스터디 카페 라운지",
        "카페",
        10,
        1,
        4.0,
        ["넓은 좌석", "조용한"],
        null,
        8,
        24,
      ],
      [
        "신촌 맥주 창고",
        "술집",
        12,
        1,
        4.1,
        ["맥주", "단체석", "가성비"],
        "생맥주 1잔 무료",
        16,
        26,
      ],
      [
        "신촌 보드 카페",
        "보드게임카페",
        8,
        1,
        4.3,
        ["보드게임", "학생 할인"],
        "학생증 제시 시 10% 할인",
        12,
        24,
      ],
      [
        "신촌 룸 이스케이프",
        "방탈출",
        6,
        2,
        4.4,
        ["협동", "스토리"],
        null,
        10,
        23,
      ],
    ],
  },
  혜화: {
    area: "서울 종로구 명륜/혜화",
    rows: [
      [
        "혜화 골목 한식",
        "음식점",
        8,
        2,
        4.3,
        ["한식", "조용한", "룸"],
        null,
        11,
        22,
      ],
      [
        "대학로 북 카페",
        "카페",
        8,
        1,
        4.4,
        ["조용한", "책", "분위기"],
        null,
        9,
        22,
      ],
      [
        "혜화 막걸리 주막",
        "술집",
        12,
        1,
        4.2,
        ["막걸리", "전", "단체석"],
        "전 메뉴 1종 서비스",
        16,
        25,
      ],
      [
        "대학로 보드게임 극장",
        "보드게임카페",
        10,
        1,
        4.2,
        ["보드게임", "공연 연계"],
        null,
        12,
        23,
      ],
      [
        "대학로 소극장 데이트",
        "기타",
        10,
        2,
        4.5,
        ["공연", "문화"],
        "공연 티켓 10% 할인",
        12,
        22,
      ],
    ],
  },
  잠실: {
    area: "서울 송파구 잠실동",
    rows: [
      [
        "잠실 호수 뷰 레스토랑",
        "음식점",
        10,
        3,
        4.5,
        ["전망", "코스", "룸"],
        null,
        11,
        23,
      ],
      [
        "석촌 호수 카페",
        "카페",
        12,
        2,
        4.4,
        ["전망", "산책", "디저트"],
        null,
        9,
        23,
      ],
      [
        "잠실 크래프트 탭룸",
        "술집",
        12,
        2,
        4.2,
        ["크래프트 맥주", "단체석"],
        "크래프트 맥주 1잔 할인",
        17,
        25,
      ],
      [
        "잠실 게임 라운지",
        "보드게임카페",
        10,
        2,
        4.3,
        ["보드게임", "룸"],
        null,
        12,
        24,
      ],
      [
        "잠실 이스케이프 존",
        "방탈출",
        6,
        2,
        4.5,
        ["추리", "공포"],
        null,
        10,
        23,
      ],
    ],
  },
  종로: {
    area: "서울 종로구 종로",
    rows: [
      [
        "종로 익선 한옥 식당",
        "음식점",
        10,
        2,
        4.4,
        ["한옥", "분위기", "룸"],
        null,
        11,
        22,
      ],
      [
        "익선 다방",
        "카페",
        10,
        1,
        4.5,
        ["한옥", "전통차", "사진"],
        "전통차 세트 10% 할인",
        10,
        22,
      ],
      [
        "종로 포장마차 거리",
        "술집",
        16,
        1,
        4.0,
        ["단체석", "가성비", "안주"],
        null,
        17,
        27,
      ],
      [
        "종로 보드 서재",
        "보드게임카페",
        8,
        1,
        4.2,
        ["보드게임", "조용한"],
        null,
        12,
        24,
      ],
      [
        "북촌 전통 체험방",
        "기타",
        12,
        2,
        4.3,
        ["체험", "이색", "활동"],
        "체험 프로그램 5% 할인",
        10,
        20,
      ],
    ],
  },
};

export const PLACES: PlaceSeed[] = Object.entries(REGION_DATA).flatMap(
  ([region, { area, rows }]) =>
    rows.map(
      (
        [
          name,
          category,
          capacityMax,
          priceLevel,
          rating,
          tags,
          perk,
          openFrom,
          openTo,
        ],
        index,
      ): PlaceSeed => ({
        id: `${region}-${index + 1}`,
        name,
        category,
        region,
        address: area,
        capacityMax,
        priceLevel,
        rating,
        tags,
        perk,
        openFrom,
        openTo,
      }),
    ),
);

export function findPlace(id: string): PlaceSeed | undefined {
  return PLACES.find((p) => p.id === id);
}

export const reservationUrl = (place: PlaceSeed): string =>
  `https://search.naver.com/search.naver?query=${encodeURIComponent(`${place.region} ${place.name} 예약`)}`;

export const mapUrl = (place: PlaceSeed): string =>
  `https://map.naver.com/p/search/${encodeURIComponent(`${place.region} ${place.name}`)}`;
